sudo: false
language: ruby
cache: bundler

rvm:
- 2.3.0
- 2.4.1

gemfile:
  - gemfiles/Gemfile.activerecord50
  - gemfiles/Gemfile.activerecord51
  - gemfiles/Gemfile.activerecord52
  - gemfiles/Gemfile.activerecord-edge

matrix:
  exclude:
    - rvm: 2.3.0
      gemfile: gemfiles/Gemfile.activerecord-edge

before_script:
- mysql -e 'create database database_validations;'
